### ISSUE TITLE
Other networks

### ISSUE THREAD

**Issue by rcsrex** [limelight-stream/limelight-ios#46] opened 2015-01-01 10:17 UTC
Has anyone else successfully used this other than their Host PC's network? Or has this not been implemented yet in the iOS version yet?

**Comment by betrisey** [comment] 2015-01-01 21:47
Yes, it works fine.
You need to allow game stream from Internet in the Nvidia Experiment Settings. The ports will be automatically forwarded.
If your router does not support UPnP IGD, you need to forward these ports :
- TCP: 35043, 47995, 47996, 47989, 47984, 48010
- UDP: 7, 9, 47999, 47998, 47989, 48000
Then in limelight, click on "add host" and enter your public IP address.

**Comment by rcsrex** [comment] 2015-01-02 04:49
Awesome. Thanks for the reply.

**Comment by Zekisu** [comment] 2015-01-02 09:24
It works via  Shield proxy after port forwarding and DMZ enabling on your home router with the host PC listed as the private IP address. My only problem is I always get a black screen. If I am on LTE, 3G, or even WiFi. I have yet to try c4all+BTstack.

**Comment by betrisey** [comment] 2015-01-02 16:32
@Zekisu Controller4all works with my Dualshock 3 (PS3 controller)
But I hhaven't found any way to connect an Xbox controller.
The black screen issue may be caused by the bitrate that you have set in the app (higher than your upload speed or download speed of your 3G/LTE network).

**Comment by rcsrex** [comment] 2015-01-22 02:34
My public IP refused to pair even when i'm on my own home network.

**Comment by dwaxemberg** [comment] 2015-02-24 21:55
Closing this since it seems to be resolved

**Closed by dwaxemberg** 2015-02-24 21:55 UTC
